defaultPortal: McKay
portals:
  - name: McKay
    portalId: 319325
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          COqa7oaPLxIEAA0ABBjdvhMgxamaBiju6QwyGQCSUocFmJYYFYjolrLbStqGnvTFze1565w6KAAABEEAAAB4AAAAAAAAAACAAAAAAAAABAAAwAdgAAAAAAAAAAAAAGBCGQCSUocFhiqNv8JJUfk_YnFR19Z0Ck5XJQ5KA25hMQ
        expiresAt: '2021-04-20T19:57:03.729Z'
    personalAccessKey: >-
      CiRiOWQxNTczOC01OWQwLTQ4MTgtOTQzNS0xNTZjNjQ5ZjdmNWQQ3b4TGMWpmgYqGQAF5pGCsBatFFochQQ0kPJ3xJ4r4tVm3hc
